tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# App to build and share containerized applications and microservices
cask "docker"
# Web browser
cask "librewolf"
# Typeface made for developers
cask "font-fira-code"
# Developer targeted fonts with a high number of glyphs
cask "font-symbols-only-nerd-font"
# Get rid of shit well
cask "appcleaner"
# Free and open-source media player
cask "vlc"
# Kittens
cask "discord"
# VM's
cask "utm"
# Video editing
cask "olive"
# Image editing
cask "gimp"
# Music streaming service
cask "spotify"
# Its in the name really
cask "mutespotifyads"
# Clipboard history
cask "maccy"
# Burn ISO's
cask "balenaetcher"

